{% set name = "neworder" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: b0436dba22043785c384f704c863c623fb4510dd508cae162ce578f38505b20f

build:
  number: 1
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >=2.6.0
    - numpy
    - pytest
    - pytest-runner
    - pip
  run:
    - numpy
    - matplotlib-base >=3.6.2
    - python
    - pandas >=1.5.0
    - pandas-stubs
    - scipy >=1.9.3

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - ocefpaf
