{% set name = "neworder" %}
{% set version = "1.0.1" %}
{% set sha256 = "647936bf347d05aecd76233c587d9e15157bbe864a6856e6a9990251e2e2daa2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11 >=2.5.0
    - pytest-runner
    - python
  run:
    - numpy >=1.19.1
    - pandas >=1.0.5
    - scipy
    - python

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - virgesmith
