{% set name = "neworder" %}
{% set version = "1.3.0" %}
{% set sha256 = "8f3ac6da4b6277f579547299f3047f7544051c42d2384c2088080947aa1947b4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11 >=2.5.0
    - numpy >=1.19.1
    - pytest-runner
    - python
  run:
    - numpy >=1.19.1
    - pandas >=1.0.5
    - scipy
    - python
    - geopandas
    - networkx
    - osmnx
    - gdal

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - virgesmith
