{% set name = "neworder" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: 95004d66a12919c1d39803bfa234701306271f8a6dd09b588bd7438800ce07f1

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >=2.6.0
    - numpy
    - pytest
    - pytest-runner
    - pip
  run:
    - matplotlib-base >=3.6.2
    - python
    - pandas >=1.5.0
    - pandas-stubs
    - scipy >=1.9.3
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - ocefpaf
