{% set name = "neworder" %}
{% set version = "0.0.8" %}
{% set sha256 = "fb94ebb7be44c1abc519bab25525e7178147bc1067928f6bfc2d1415b0948261" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11 >=2.5.0
    - pytest-runner
    - python
  run:
    - numpy >=1.19.1
    - pandas >=1.0.5
    - python

test:
  imports:
    - neworder
    - neworder.test
  commands:
    - pip check
    - pytest -sv
  requires:
    - pip
    - pytest

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - virgesmith
