{% set name = "neworder" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neworder-{{ version }}.tar.gz
  sha256: 864125afa9ef015fdf1b03f3ffb1bde6c5bcade90685eacbf64539db278e1e8d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >=2.6.0
    - numpy
    - pytest
    - pytest-runner
    - pip
  run:
    - python
    - pandas >=1.0.5
    - pandas-stubs
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - neworder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://neworder.readthedocs.io
  summary: A dynamic microsimulation framework
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - ocefpaf
